#!/usr/bin/env node
/**
 * Groit rules generator.
 *
 * Reads the knowledge graph and emits agent-facing context files into the
 * target repo: CLAUDE.md (Claude Code) and .cursor/rules/groit-domain.mdc
 * (Cursor). Only knowledge that clears the confidence bar is emitted as
 * hard rules; everything below it is emitted as labelled uncertainty —
 * Groit never lets a guess masquerade as a fact.
 *
 * Usage: node generate-rules.mjs [--graph <path>] [--target <repo path>]
 */
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const CONFIDENCE_BAR = 0.75;

const args = process.argv.slice(2);
function argValue(flag, fallback) {
  const i = args.indexOf(flag);
  return i !== -1 && args[i + 1] ? args[i + 1] : fallback;
}

const graphPath = resolve(argValue('--graph', join(HERE, 'knowledge', 'graph.json')));
const targetRepo = resolve(argValue('--target', join(HERE, '..', 'appeals-service')));

// First run convenience: materialize the working graph from the seed.
if (!existsSync(graphPath)) {
  const seed = join(dirname(graphPath), 'graph.seed.json');
  if (!existsSync(seed)) {
    console.error(`No graph at ${graphPath} and no seed to copy. Aborting.`);
    process.exit(1);
  }
  copyFileSync(seed, graphPath);
  console.log(`Initialized working graph from seed: ${graphPath}`);
}

const graph = JSON.parse(readFileSync(graphPath, 'utf8'));

const badge = (p) => (p.type === 'human' ? '✅ human-verified' : p.type === 'trace' ? `🔗 trace-derived` : '🤖 code-derived');
const pct = (c) => `${Math.round(c * 100)}%`;
const codeRefs = (links = []) => links.map((l) => `\`${l.file}\` (\`${l.symbol}\`)`).join(', ');

const isVerified = (c) => c.status === 'verified' || c.provenance.type === 'human';
const clearsBar = (c) => isVerified(c) || c.confidence >= CONFIDENCE_BAR;

const invariants = graph.claims.filter((c) => c.classification === 'invariant' && clearsBar(c));
const accidents = graph.claims.filter((c) => c.classification === 'accident' && isVerified(c));
const hypotheses = graph.claims.filter((c) => !invariants.includes(c) && !accidents.includes(c));
const openQuestions = graph.questions.filter((q) => q.status === 'open');

function claimBlock(c, i) {
  const lines = [
    `### INV-${i + 1}: ${c.statement}`,
    '',
    `*${badge(c.provenance)} · confidence ${pct(c.confidence)} · source: ${c.provenance.source}*`,
    '',
    `**Why:** ${c.why}`,
    '',
    `**Code:** ${codeRefs(c.codeLinks)}`,
  ];
  return lines.join('\n');
}

const sections = [];

sections.push(`# Domain knowledge — ${graph.project}

> Generated by **Groit** from the team knowledge graph on ${new Date().toISOString().slice(0, 10)}.
> Do not edit by hand — correct Groit instead, and the change is captured permanently.
>
> Provenance legend: ✅ human-verified · 🔗 trace-derived (extracted from PRs/commits) · 🤖 code-derived hypothesis.`);

sections.push(`## Business invariants — DO NOT change without the cited sign-off

${invariants.length ? invariants.map(claimBlock).join('\n\n') : '_None recorded yet._'}`);

const termRows = graph.terms
  .map((t) => {
    const ctx = graph.contexts.find((x) => x.id === t.contextId)?.name ?? t.contextId;
    return `| **${t.term}** | ${ctx} | ${t.definition} | ${t.codeSymbols.map((s) => `\`${s}\``).join(', ')} |`;
  })
  .join('\n');

const aliasNotes = graph.terms
  .flatMap((t) =>
    (t.aliases ?? []).map((a) => {
      const ctx = graph.contexts.find((x) => x.id === a.contextId)?.name ?? a.contextId;
      return `- ⚠️ **${a.term}** (${ctx}) is the **same concept** as **${t.term}**. ${a.note}`;
    }),
  )
  .join('\n');

sections.push(`## Ubiquitous language

| Term | Context | Definition | Code |
|---|---|---|---|
${termRows}

${aliasNotes ? `### Terminology traps\n\n${aliasNotes}` : ''}`);

sections.push(`## Verified accidents — safe to clean up

${
  accidents.length
    ? accidents
        .map(
          (c) =>
            `- ${c.statement}\n  *${badge(c.provenance)} by ${c.provenance.author} (${c.provenance.date}) — ${c.why}*\n  Code: ${codeRefs(c.codeLinks)}`,
        )
        .join('\n')
    : '_None verified yet. Oddities without a verified explanation appear under Open questions below — do not assume they are safe to remove._'
}`);

if (hypotheses.length) {
  sections.push(`## Unverified hypotheses — treat with care

${hypotheses
  .map((c) => `- ${c.statement} *(${badge(c.provenance)}, confidence ${pct(c.confidence)} — below the ${pct(CONFIDENCE_BAR)} bar for a hard rule)*`)
  .join('\n')}`);
}

sections.push(`## Open questions — ask a human BEFORE touching this code

${
  openQuestions.length
    ? openQuestions
        .map(
          (q) =>
            `- **${q.id}** — ${q.question}\n  *Routed to: ${q.routedTo.name} (${q.routedTo.basis}).*\n  Code: ${codeRefs(q.codeLinks)}\n  **Until answered, treat this code as intentional and leave it in place.**`,
        )
        .join('\n')
    : '_No open questions._'
}`);

sections.push(`## How to use this file (for AI assistants)

1. Before modifying any file listed under an invariant, re-read the invariant. If a change would violate it, refuse and cite the rule id and its source.
2. Tests passing is NOT sufficient evidence that a change is safe — INV rules exist precisely where the test suite is blind.
3. Use the ubiquitous language above in code, comments, and commit messages. Never introduce a third name for an existing concept.
4. Code under an open question must be treated as intentional. Flag the question id instead of "cleaning it up".`);

const body = sections.join('\n\n');

// CLAUDE.md
const claudePath = join(targetRepo, 'CLAUDE.md');
writeFileSync(claudePath, body + '\n');

// Cursor rules
const cursorDir = join(targetRepo, '.cursor', 'rules');
mkdirSync(cursorDir, { recursive: true });
const cursorPath = join(cursorDir, 'groit-domain.mdc');
writeFileSync(
  cursorPath,
  `---
description: Groit domain knowledge for ${graph.project} (generated — do not edit)
globs:
alwaysApply: true
---

${body}
`,
);

console.log(`Groit → wrote ${claudePath}`);
console.log(`Groit → wrote ${cursorPath}`);
console.log(
  `  ${invariants.length} invariant(s), ${graph.terms.length} term(s), ${accidents.length} verified accident(s), ${hypotheses.length} unverified hypothesis(es), ${openQuestions.length} open question(s)`,
);
