#!/usr/bin/env node
/**
 * ContextCaddy rules generator (prong 4: domain-aware agents).
 *
 * Reads the team knowledge graph — domains, business functions, and the
 * daily-huddle queue — and emits agent-facing context files into the target
 * repo: CLAUDE.md (Claude Code) and .cursor/rules/contextcaddy-domain.mdc (Cursor).
 * Only knowledge that clears the confidence bar is emitted as hard rules;
 * everything below it is emitted as labelled uncertainty — ContextCaddy never lets
 * a guess masquerade as a fact.
 *
 * Usage: node generate-rules.mjs [--graph <path>] [--target <repo path>]
 */
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const CONFIDENCE_BAR = 0.75;

const args = process.argv.slice(2);
function argValue(flag, fallback) {
  const i = args.indexOf(flag);
  return i !== -1 && args[i + 1] ? args[i + 1] : fallback;
}

const graphPath = resolve(argValue('--graph', join(HERE, 'knowledge', 'graph.json')));
const targetRepo = resolve(argValue('--target', join(HERE, '..', 'appeals-service')));

// First run convenience: materialize the working graph from the seed.
if (!existsSync(graphPath)) {
  const seed = join(dirname(graphPath), 'graph.seed.json');
  if (!existsSync(seed)) {
    console.error(`No graph at ${graphPath} and no seed to copy. Aborting.`);
    process.exit(1);
  }
  copyFileSync(seed, graphPath);
  console.log(`Initialized working graph from seed: ${graphPath}`);
}

const graph = JSON.parse(readFileSync(graphPath, 'utf8'));

const badge = (p) => (p.type === 'human' ? '✅ human-verified' : p.type === 'trace' ? '🔗 trace-derived' : '🤖 code-derived');
const pct = (c) => `${Math.round(c * 100)}%`;
const codeRefs = (links = []) => links.map((l) => `\`${l.file}\` (\`${l.symbol}\`)`).join(', ');
const stripTargetPrefix = (p) => (p ? p.replace(/^appeals-service\//, '') : p);

const isVerified = (r) => r.status === 'verified' || r.provenance.type === 'human';
const clearsBar = (r) => isVerified(r) || r.confidence >= CONFIDENCE_BAR;

// Rules live on both domains and functions; tag each with its owner.
const allRules = [
  ...graph.domains.flatMap((d) => d.rules.map((r) => ({ ...r, owner: d.name, ownerKind: 'domain' }))),
  ...graph.functions.flatMap((f) => f.rules.map((r) => ({ ...r, owner: f.name, ownerKind: 'function' }))),
];

const invariants = allRules.filter((r) => r.classification === 'invariant' && clearsBar(r));
const accidents = allRules.filter((r) => r.classification === 'accident' && isVerified(r));
const hypotheses = allRules.filter((r) => !invariants.includes(r) && !accidents.includes(r));
// Share-type items (design decisions, spec changes circulated for awareness)
// don't gate code edits — only unresolved flags do.
const GATING_KINDS = new Set(['divergence', 'oddity', 'terminology']);
const openItems = graph.huddle.items.filter((i) => i.status === 'open' && GATING_KINDS.has(i.kind));
const decisions = graph.huddle.items.filter((i) => i.status === 'resolved');

const sections = [];

sections.push(`# Domain knowledge — ${graph.project}

> Generated by **ContextCaddy** from the team knowledge graph on ${new Date().toISOString().slice(0, 10)}.
> Do not edit by hand — the graph is maintained by the team's specs, commit
> history, and daily huddle; correct it there and regenerate.
>
> Provenance legend: ✅ human-verified · 🔗 trace-derived (extracted from specs/commits/PRs) · 🤖 code-derived hypothesis.`);

const domainRows = graph.domains
  .map((d) => `| **${d.name}** | ${d.description} | \`${stripTargetPrefix(d.spec)}\` |`)
  .join('\n');

const aliasNotes = graph.domains
  .flatMap((d) =>
    (d.aliases ?? []).map((a) => `- ⚠️ **${a.term}** (${a.where}) is the **same concept** as **${d.name}**. ${a.note}`),
  )
  .join('\n');

sections.push(`## Domain language

| Domain | Meaning | Spec |
|---|---|---|
${domainRows}

${aliasNotes ? `### Terminology traps\n\n${aliasNotes}` : ''}`);

const byOwner = new Map();
for (const r of invariants) {
  if (!byOwner.has(r.owner)) byOwner.set(r.owner, []);
  byOwner.get(r.owner).push(r);
}

let invIndex = 0;
const invariantBlocks = [...byOwner.entries()]
  .map(([owner, rules]) => {
    const blocks = rules.map((r) => {
      invIndex += 1;
      return [
        `### INV-${invIndex}: ${r.statement}`,
        '',
        `*${r.owner} · ${badge(r.provenance)} · confidence ${pct(r.confidence)} · source: ${r.provenance.source}*`,
        '',
        `**Why:** ${r.why}`,
        '',
        `**Code:** ${codeRefs(r.codeLinks)}`,
      ].join('\n');
    });
    return blocks.join('\n\n');
  })
  .join('\n\n');

sections.push(`## Business invariants — DO NOT change without the cited sign-off

${invariants.length ? invariantBlocks : '_None recorded yet._'}`);

sections.push(`## Verified accidents — safe to clean up

${
  accidents.length
    ? accidents
        .map(
          (r) =>
            `- ${r.statement}\n  *${badge(r.provenance)} by ${r.provenance.author} (${r.provenance.date}) — ${r.why}*\n  Code: ${codeRefs(r.codeLinks)}`,
        )
        .join('\n')
    : '_None verified yet. Oddities without a verified explanation appear in the huddle queue below — do not assume they are safe to remove._'
}`);

if (hypotheses.length) {
  sections.push(`## Unverified hypotheses — treat with care

${hypotheses
  .map((r) => `- ${r.statement} *(${r.owner} · ${badge(r.provenance)}, confidence ${pct(r.confidence)} — below the ${pct(CONFIDENCE_BAR)} bar for a hard rule)*`)
  .join('\n')}`);
}

sections.push(`## Open huddle items — ask a human BEFORE touching this code

${
  openItems.length
    ? openItems
        .map(
          (i) =>
            `- **${i.id}** (${i.kind}) — ${i.title}\n  ${i.detail}\n  *Routed to: ${i.routedTo.name} (${i.routedTo.basis}).*\n  **Until the huddle resolves this, treat the code as intentional and leave it in place.**`,
        )
        .join('\n')
    : '_No open items — the huddle queue is clear._'
}`);

if (decisions.length) {
  sections.push(`## Recent huddle decisions

${decisions
  .map((i) => `- **${i.id}** (${i.resolution.date}) — ${i.title}\n  **Decision:** ${i.resolution.action} *(owner: ${i.resolution.owner}; recorded by ${i.resolution.recordedBy})*`)
  .join('\n')}`);
}

sections.push(`## How to use this file (for AI assistants)

1. Before modifying any file listed under an invariant, re-read the invariant. If a change would violate it, refuse and cite the rule id and its source.
2. Tests passing is NOT sufficient evidence that a change is safe — INV rules exist precisely where the test suite is blind.
3. Use the domain language above in code, comments, and commit messages. Never introduce a third name for an existing concept.
4. Code under an open huddle item must be treated as intentional. Flag the item id instead of "cleaning it up".
5. The specs under \`specs/\` are the source of truth. If a change makes code diverge from its spec, say so in the commit body and flag it for the daily huddle.`);

const body = sections.join('\n\n');

// CLAUDE.md
const claudePath = join(targetRepo, 'CLAUDE.md');
writeFileSync(claudePath, body + '\n');

// Cursor rules
const cursorDir = join(targetRepo, '.cursor', 'rules');
mkdirSync(cursorDir, { recursive: true });
const cursorPath = join(cursorDir, 'contextcaddy-domain.mdc');
writeFileSync(
  cursorPath,
  `---
description: ContextCaddy domain knowledge for ${graph.project} (generated — do not edit)
globs:
alwaysApply: true
---

${body}
`,
);

console.log(`ContextCaddy → wrote ${claudePath}`);
console.log(`ContextCaddy → wrote ${cursorPath}`);
console.log(
  `  ${graph.domains.length} domain(s), ${graph.functions.length} function(s), ${invariants.length} invariant(s), ${accidents.length} verified accident(s), ${hypotheses.length} unverified hypothesis(es), ${openItems.length} open huddle item(s)`,
);
